// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: parser/protobuf/nodetype.proto

package parser

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AstNodeTypeEnumProto int32

const (
	AstNodeTypeEnumProto_Document           AstNodeTypeEnumProto = 0
	AstNodeTypeEnumProto_Text               AstNodeTypeEnumProto = 1
	AstNodeTypeEnumProto_Header             AstNodeTypeEnumProto = 2
	AstNodeTypeEnumProto_MathBlock          AstNodeTypeEnumProto = 3
	AstNodeTypeEnumProto_CodeBlock          AstNodeTypeEnumProto = 4
	AstNodeTypeEnumProto_HorizontalRule     AstNodeTypeEnumProto = 5
	AstNodeTypeEnumProto_TableHead          AstNodeTypeEnumProto = 6
	AstNodeTypeEnumProto_TableAlign         AstNodeTypeEnumProto = 7
	AstNodeTypeEnumProto_TableLine          AstNodeTypeEnumProto = 8
	AstNodeTypeEnumProto_Table              AstNodeTypeEnumProto = 9
	AstNodeTypeEnumProto_QuoteBlock         AstNodeTypeEnumProto = 10
	AstNodeTypeEnumProto_List               AstNodeTypeEnumProto = 11
	AstNodeTypeEnumProto_ListItem           AstNodeTypeEnumProto = 12
	AstNodeTypeEnumProto_Emphasis           AstNodeTypeEnumProto = 13
	AstNodeTypeEnumProto_Italic             AstNodeTypeEnumProto = 14
	AstNodeTypeEnumProto_StrikeThrough      AstNodeTypeEnumProto = 15
	AstNodeTypeEnumProto_Code               AstNodeTypeEnumProto = 16
	AstNodeTypeEnumProto_Math               AstNodeTypeEnumProto = 17
	AstNodeTypeEnumProto_Link               AstNodeTypeEnumProto = 18
	AstNodeTypeEnumProto_SimpleLink         AstNodeTypeEnumProto = 19
	AstNodeTypeEnumProto_ReferenceLink      AstNodeTypeEnumProto = 20
	AstNodeTypeEnumProto_ReferenceLinkIndex AstNodeTypeEnumProto = 21
	AstNodeTypeEnumProto_FootNote           AstNodeTypeEnumProto = 22
	AstNodeTypeEnumProto_FootNoteIndex      AstNodeTypeEnumProto = 23
	AstNodeTypeEnumProto_Image              AstNodeTypeEnumProto = 24
	AstNodeTypeEnumProto_HtmlStartTag       AstNodeTypeEnumProto = 25
	AstNodeTypeEnumProto_HtmlEndTag         AstNodeTypeEnumProto = 26
)

// Enum value maps for AstNodeTypeEnumProto.
var (
	AstNodeTypeEnumProto_name = map[int32]string{
		0:  "Document",
		1:  "Text",
		2:  "Header",
		3:  "MathBlock",
		4:  "CodeBlock",
		5:  "HorizontalRule",
		6:  "TableHead",
		7:  "TableAlign",
		8:  "TableLine",
		9:  "Table",
		10: "QuoteBlock",
		11: "List",
		12: "ListItem",
		13: "Emphasis",
		14: "Italic",
		15: "StrikeThrough",
		16: "Code",
		17: "Math",
		18: "Link",
		19: "SimpleLink",
		20: "ReferenceLink",
		21: "ReferenceLinkIndex",
		22: "FootNote",
		23: "FootNoteIndex",
		24: "Image",
		25: "HtmlStartTag",
		26: "HtmlEndTag",
	}
	AstNodeTypeEnumProto_value = map[string]int32{
		"Document":           0,
		"Text":               1,
		"Header":             2,
		"MathBlock":          3,
		"CodeBlock":          4,
		"HorizontalRule":     5,
		"TableHead":          6,
		"TableAlign":         7,
		"TableLine":          8,
		"Table":              9,
		"QuoteBlock":         10,
		"List":               11,
		"ListItem":           12,
		"Emphasis":           13,
		"Italic":             14,
		"StrikeThrough":      15,
		"Code":               16,
		"Math":               17,
		"Link":               18,
		"SimpleLink":         19,
		"ReferenceLink":      20,
		"ReferenceLinkIndex": 21,
		"FootNote":           22,
		"FootNoteIndex":      23,
		"Image":              24,
		"HtmlStartTag":       25,
		"HtmlEndTag":         26,
	}
)

func (x AstNodeTypeEnumProto) Enum() *AstNodeTypeEnumProto {
	p := new(AstNodeTypeEnumProto)
	*p = x
	return p
}

func (x AstNodeTypeEnumProto) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AstNodeTypeEnumProto) Descriptor() protoreflect.EnumDescriptor {
	return file_parser_protobuf_nodetype_proto_enumTypes[0].Descriptor()
}

func (AstNodeTypeEnumProto) Type() protoreflect.EnumType {
	return &file_parser_protobuf_nodetype_proto_enumTypes[0]
}

func (x AstNodeTypeEnumProto) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AstNodeTypeEnumProto.Descriptor instead.
func (AstNodeTypeEnumProto) EnumDescriptor() ([]byte, []int) {
	return file_parser_protobuf_nodetype_proto_rawDescGZIP(), []int{0}
}

type AstNodeTypeProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Which  AstNodeTypeEnumProto `protobuf:"varint,1,opt,name=which,proto3,enum=parser.AstNodeTypeEnumProto" json:"which,omitempty"`
	Encode []byte               `protobuf:"bytes,2,opt,name=encode,proto3" json:"encode,omitempty"`
}

func (x *AstNodeTypeProto) Reset() {
	*x = AstNodeTypeProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parser_protobuf_nodetype_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AstNodeTypeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AstNodeTypeProto) ProtoMessage() {}

func (x *AstNodeTypeProto) ProtoReflect() protoreflect.Message {
	mi := &file_parser_protobuf_nodetype_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AstNodeTypeProto.ProtoReflect.Descriptor instead.
func (*AstNodeTypeProto) Descriptor() ([]byte, []int) {
	return file_parser_protobuf_nodetype_proto_rawDescGZIP(), []int{0}
}

func (x *AstNodeTypeProto) GetWhich() AstNodeTypeEnumProto {
	if x != nil {
		return x.Which
	}
	return AstNodeTypeEnumProto_Document
}

func (x *AstNodeTypeProto) GetEncode() []byte {
	if x != nil {
		return x.Encode
	}
	return nil
}

type PosProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Line   int32 `protobuf:"varint,1,opt,name=line,proto3" json:"line,omitempty"`
	Col    int32 `protobuf:"varint,2,opt,name=col,proto3" json:"col,omitempty"`
	Offset int32 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *PosProto) Reset() {
	*x = PosProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parser_protobuf_nodetype_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PosProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PosProto) ProtoMessage() {}

func (x *PosProto) ProtoReflect() protoreflect.Message {
	mi := &file_parser_protobuf_nodetype_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PosProto.ProtoReflect.Descriptor instead.
func (*PosProto) Descriptor() ([]byte, []int) {
	return file_parser_protobuf_nodetype_proto_rawDescGZIP(), []int{1}
}

func (x *PosProto) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *PosProto) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

func (x *PosProto) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type AstNodeProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        *AstNodeTypeProto `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Start       *PosProto         `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End         *PosProto         `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	Parent      int32             `protobuf:"varint,4,opt,name=parent,proto3" json:"parent,omitempty"`
	Leftsibling int32             `protobuf:"varint,5,opt,name=leftsibling,proto3" json:"leftsibling,omitempty"`
	Children    []int32           `protobuf:"varint,6,rep,packed,name=children,proto3" json:"children,omitempty"`
}

func (x *AstNodeProto) Reset() {
	*x = AstNodeProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parser_protobuf_nodetype_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AstNodeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AstNodeProto) ProtoMessage() {}

func (x *AstNodeProto) ProtoReflect() protoreflect.Message {
	mi := &file_parser_protobuf_nodetype_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AstNodeProto.ProtoReflect.Descriptor instead.
func (*AstNodeProto) Descriptor() ([]byte, []int) {
	return file_parser_protobuf_nodetype_proto_rawDescGZIP(), []int{2}
}

func (x *AstNodeProto) GetType() *AstNodeTypeProto {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *AstNodeProto) GetStart() *PosProto {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *AstNodeProto) GetEnd() *PosProto {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *AstNodeProto) GetParent() int32 {
	if x != nil {
		return x.Parent
	}
	return 0
}

func (x *AstNodeProto) GetLeftsibling() int32 {
	if x != nil {
		return x.Leftsibling
	}
	return 0
}

func (x *AstNodeProto) GetChildren() []int32 {
	if x != nil {
		return x.Children
	}
	return nil
}

type AstProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*AstNodeProto `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *AstProto) Reset() {
	*x = AstProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parser_protobuf_nodetype_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AstProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AstProto) ProtoMessage() {}

func (x *AstProto) ProtoReflect() protoreflect.Message {
	mi := &file_parser_protobuf_nodetype_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AstProto.ProtoReflect.Descriptor instead.
func (*AstProto) Descriptor() ([]byte, []int) {
	return file_parser_protobuf_nodetype_proto_rawDescGZIP(), []int{3}
}

func (x *AstProto) GetNodes() []*AstNodeProto {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_parser_protobuf_nodetype_proto protoreflect.FileDescriptor

var file_parser_protobuf_nodetype_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x06, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x22, 0x5e, 0x0a, 0x10, 0x41, 0x73, 0x74, 0x4e,
	0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x32, 0x0a, 0x05,
	0x77, 0x68, 0x69, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x70, 0x61,
	0x72, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x73, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x45, 0x6e, 0x75, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x05, 0x77, 0x68, 0x69, 0x63, 0x68,
	0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x48, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6f, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x63, 0x6f, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x22, 0xde, 0x01, 0x0a, 0x0c, 0x41, 0x73, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x2c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x73, 0x74, 0x4e, 0x6f,
	0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x26, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2e, 0x50, 0x6f, 0x73, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x22, 0x0a, 0x03, 0x65, 0x6e, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2e,
	0x50, 0x6f, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x65, 0x66, 0x74, 0x73, 0x69, 0x62,
	0x6c, 0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6c, 0x65, 0x66, 0x74,
	0x73, 0x69, 0x62, 0x6c, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64,
	0x72, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x03, 0x28, 0x05, 0x52, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64,
	0x72, 0x65, 0x6e, 0x22, 0x36, 0x0a, 0x08, 0x41, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x2a, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x73, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x2a, 0xa1, 0x03, 0x0a, 0x14,
	0x41, 0x73, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x61, 0x74, 0x68,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x6f, 0x64, 0x65, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x10, 0x04, 0x12, 0x12, 0x0a, 0x0e, 0x48, 0x6f, 0x72, 0x69, 0x7a, 0x6f,
	0x6e, 0x74, 0x61, 0x6c, 0x52, 0x75, 0x6c, 0x65, 0x10, 0x05, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x48, 0x65, 0x61, 0x64, 0x10, 0x06, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x41, 0x6c, 0x69, 0x67, 0x6e, 0x10, 0x07, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x10, 0x08, 0x12, 0x09, 0x0a, 0x05, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x10, 0x09, 0x12, 0x0e, 0x0a, 0x0a, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x10, 0x0a, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x10, 0x0b, 0x12, 0x0c, 0x0a,
	0x08, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x10, 0x0c, 0x12, 0x0c, 0x0a, 0x08, 0x45,
	0x6d, 0x70, 0x68, 0x61, 0x73, 0x69, 0x73, 0x10, 0x0d, 0x12, 0x0a, 0x0a, 0x06, 0x49, 0x74, 0x61,
	0x6c, 0x69, 0x63, 0x10, 0x0e, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x74, 0x72, 0x69, 0x6b, 0x65, 0x54,
	0x68, 0x72, 0x6f, 0x75, 0x67, 0x68, 0x10, 0x0f, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x10, 0x10, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x61, 0x74, 0x68, 0x10, 0x11, 0x12, 0x08, 0x0a, 0x04,
	0x4c, 0x69, 0x6e, 0x6b, 0x10, 0x12, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65,
	0x4c, 0x69, 0x6e, 0x6b, 0x10, 0x13, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x10, 0x14, 0x12, 0x16, 0x0a, 0x12, 0x52, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x10,
	0x15, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x6f, 0x6f, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x10, 0x16, 0x12,
	0x11, 0x0a, 0x0d, 0x46, 0x6f, 0x6f, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x10, 0x17, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x10, 0x18, 0x12, 0x10, 0x0a,
	0x0c, 0x48, 0x74, 0x6d, 0x6c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x61, 0x67, 0x10, 0x19, 0x12,
	0x0e, 0x0a, 0x0a, 0x48, 0x74, 0x6d, 0x6c, 0x45, 0x6e, 0x64, 0x54, 0x61, 0x67, 0x10, 0x1a, 0x42,
	0x09, 0x5a, 0x07, 0x2f, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_parser_protobuf_nodetype_proto_rawDescOnce sync.Once
	file_parser_protobuf_nodetype_proto_rawDescData = file_parser_protobuf_nodetype_proto_rawDesc
)

func file_parser_protobuf_nodetype_proto_rawDescGZIP() []byte {
	file_parser_protobuf_nodetype_proto_rawDescOnce.Do(func() {
		file_parser_protobuf_nodetype_proto_rawDescData = protoimpl.X.CompressGZIP(file_parser_protobuf_nodetype_proto_rawDescData)
	})
	return file_parser_protobuf_nodetype_proto_rawDescData
}

var file_parser_protobuf_nodetype_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_parser_protobuf_nodetype_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_parser_protobuf_nodetype_proto_goTypes = []interface{}{
	(AstNodeTypeEnumProto)(0), // 0: parser.AstNodeTypeEnumProto
	(*AstNodeTypeProto)(nil),  // 1: parser.AstNodeTypeProto
	(*PosProto)(nil),          // 2: parser.PosProto
	(*AstNodeProto)(nil),      // 3: parser.AstNodeProto
	(*AstProto)(nil),          // 4: parser.AstProto
}
var file_parser_protobuf_nodetype_proto_depIdxs = []int32{
	0, // 0: parser.AstNodeTypeProto.which:type_name -> parser.AstNodeTypeEnumProto
	1, // 1: parser.AstNodeProto.type:type_name -> parser.AstNodeTypeProto
	2, // 2: parser.AstNodeProto.start:type_name -> parser.PosProto
	2, // 3: parser.AstNodeProto.end:type_name -> parser.PosProto
	3, // 4: parser.AstProto.nodes:type_name -> parser.AstNodeProto
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_parser_protobuf_nodetype_proto_init() }
func file_parser_protobuf_nodetype_proto_init() {
	if File_parser_protobuf_nodetype_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_parser_protobuf_nodetype_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AstNodeTypeProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parser_protobuf_nodetype_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PosProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parser_protobuf_nodetype_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AstNodeProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parser_protobuf_nodetype_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AstProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_parser_protobuf_nodetype_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_parser_protobuf_nodetype_proto_goTypes,
		DependencyIndexes: file_parser_protobuf_nodetype_proto_depIdxs,
		EnumInfos:         file_parser_protobuf_nodetype_proto_enumTypes,
		MessageInfos:      file_parser_protobuf_nodetype_proto_msgTypes,
	}.Build()
	File_parser_protobuf_nodetype_proto = out.File
	file_parser_protobuf_nodetype_proto_rawDesc = nil
	file_parser_protobuf_nodetype_proto_goTypes = nil
	file_parser_protobuf_nodetype_proto_depIdxs = nil
}
